ALTER TABLE `email_activity` CHANGE COLUMN `subject` `subject` LONGTEXT NULL DEFAULT NULL ;
ALTER TABLE `email_activity` CHANGE COLUMN `emailTo` `emailTo` LONGTEXT NULL DEFAULT NULL ;
ALTER TABLE `email_activity` CHANGE COLUMN `cc` `cc` LONGTEXT NULL DEFAULT NULL ;
